import NavBar from "./NavBar";
import styles from '@/styles/Home.module.css'
import Head from "next/head";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Shop app</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className={styles.main}>{children}</main>
            <ToastContainer />
        </>
    );
};

export default Layout;